# Generated by Django 5.2.1 on 2025-06-09 15:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('ikon', models.CharField(blank=True, max_length=50, null=True)),
                ('warna', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tanggal', models.DateField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tipe', models.CharField(choices=[('PEMASUKAN', 'Pemasukan'), ('PENGELUARAN', 'Pengeluaran')], max_length=20)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kategori')),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPemasukan',
            fields=[
                ('transaksi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transaksi')),
                ('sumber_pemasukan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transaksi Pemasukan',
            },
            bases=('main.transaksi',),
        ),
        migrations.CreateModel(
            name='TransaksiPengeluaran',
            fields=[
                ('transaksi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transaksi')),
                ('metode_pembayaran', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transaksi Pengeluaran',
            },
            bases=('main.transaksi',),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
